vse: &vse
  docker:
    - image: circleci/node:8.11.3
configure_image: &configure_image
  steps:
    - run: sudo apt-get update
    - run: sudo apt-get install python
    - run: sudo apt-get install python-pip
    - run: sudo pip install -U pip setuptools
    - run: sudo pip install ansible boto boto3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: [*vse, *configure_image]

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - configure_image:
         requires:
           - build
      - deploy:
         requires:
           - configure_image
