vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: apt-get update
      - run: apt-get install python3
        run: pip3 install ansible boto boto3

workflows:
  version: 2.1
  build:
    jobs:
      - build