vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  configure_image:
    <<: *vse
    steps:
      - attach_workspace:
          at: .
      - run: docker build -t vm:1 ./.circleci/images/
  deploy:
    <<: *vse
    steps:
      - run: ansible --help

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - configure_image:
         requires:
           - build
      - deploy:
         requires:
           - configure_image
