image: &image
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *image
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: *image
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python
      - run: sudo apt-get install python-pip
      - run: sudo pip install -U pip setuptools
      - run: sudo pip install ansible boto boto3
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "ba:b7:67:a4:18:6a:3a:f4:e3:9e:e3:40:08:c7:26:6c"
      - run:
          command: sudo ansible-playbook ./ansible/ec2deploy.yml --user ubuntu --ssh-common-args='-o StrictHostKeyChecking=no' --private-key ~/.ssh/id_rsa_bab767a4186a3af4e39ee34008c7266c



workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
          - build
         filters:
          branches:
           only: master
