image: &image
  docker:
    - image: circleci/node:8.11.3

configure: &configure
  steps:
    - run: sudo apt-get update
    - run: sudo apt-get install python
    - run: sudo apt-get install python-pip
    - run: sudo pip install -U pip setuptools
    - run: sudo pip install ansible boto boto3

deploy: &deploy
  steps:
    - run: ansible --help

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: [*image, *configure, *deploy]

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
