image: &image
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *image
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: *image
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python
      - run: sudo apt-get install python-pip
      - run: sudo pip install -U pip setuptools
      - run: sudo pip install ansible boto boto3
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "f7:6d:d1:14:09:b3:cd:41:b4:1c:07:e0:6a:22:ab:ca"
      - run:
          command: sudo ansible-playbook ./ansible/ec2deploy.yml --user ubuntu --ssh-common-args='-o StrictHostKeyChecking=no' --private-key ~/.ssh/id_rsa_f76dd11409b3cd41b41c07e06a22abca



workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
          - build
         filters:
          branches:
           only: master
