- name: deploy to ec2
  hosts: localhost
  connection: local

  tasks:
   - name: Launch ec2 instance
     ec2:
      instance_type: t2.micro
      image: ami-085925f297f89fce1
      region: us-east-1
      key_name: presentation
      vpc_subnet_id: subnet-020af364
      assign_public_ip: yes
      wait: yes
      count: 1
      group: eshop
      aws_access_key: "ASIAR2D6UJOZPOAIOICR"
      aws_secret_key: "oSYj+qtr/Y+I9f+CD0SrcPF3/ntlAmiD4Mv6Nu51"
      security_token: "FwoGZXIvYXdzEEAaDF7P11cH5COqQb/2yiK8AWd1qKN+4CutZwX0+6ZMHRy62fLJBQWm/Qn99cYZ7aUiMtIQVX8dHKT6Rp7Vum1lvPuXJ0m8YmYBEEo4EhNQ0WFVJRqmyPZwA/KccpUcuTnZ7Cq1ldvygslnYmkQFcfkNuuZF80bUJDHM60JI8lKDJk9Mr6SyrQslbzt4BNkF/+lhRUSaI/5yd60L9SfiezHUOvZBdfmGnMSSj/+vVT6xQQESfkyUy2r9ZOEz7tN1nbp03eBcTi/KOBfQxALKNe09fUFMi0BaRfb6rvn+fbbQPiWua2vnaQUzDAy2JyB6vo3w/qBVEo9C3W5JA9reouejSw="
     register: ec2

   - name: Add instance host to group
     add_host: hostname={{item.public_dns_name}} groupname=launched
     with_items: '{{ec2.instances}}'

   - name: Wait for SSH connection
     wait_for: host={{item.public_dns_name}} port=22 delay=30 timeout=300 state=started
     with_items: '{{ec2.instances}}'

- name: Configure ec2
  hosts: launched
  connection: ssh

  tasks:
   - name: Install docker
     apt:
      name: docker.io
      state: present
      update_cache: yes
     become: yes
   - service:
      name: docker
      state: started
      enabled: yes
     become: yes
   - name: Get project from git
     git:
      repo : 'https://github.com/jakmol/4IT572_Eshop'
      dest: ./app
     become: yes
   - name: Build docker with eshop
     shell: cd app && docker build -t myeshop:latest .
     become: yes
   - name: Build docker with eshop
     shell: docker run -p 80:3000 myeshop
     async: 45
     poll: 10
     become: yes
   - wait_for:
      port: 80  
